# Generated by Django 3.2.11 on 2022-02-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tododb',
            name='date',
            field=models.DateField(default='1999-01-01'),
            preserve_default=False,
        ),
    ]
